/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Acciones.*;
import Reportes.*;
import Interprete.Interprete;
import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import java.awt.Component;
import java.awt.event.ComponentListener;
import java.io.File;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import sun.swing.FilePane;

/**
 * Esta es la pantalla principal de la aplicacion
 * @author johnnybravo
 */
public class PanelPrincipal extends javax.swing.JFrame {
 
  
    int contadorPestanas=0;
    JFileChooser seleccion=new JFileChooser();
    File archivo;
    GestionArchivo gestion=new GestionArchivo();
    public static LinkedList<ErrorT> LErrores=new LinkedList<ErrorT>();
    /**
     * Constructor  PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pestanas = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JEditorPane();
        PanelEXP = new javax.swing.JLabel();
        PanelAST = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemNuevo = new javax.swing.JMenuItem();
        itemAbrir = new javax.swing.JMenuItem();
        itemGuardar = new javax.swing.JMenuItem();
        itemCerrar = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemEjecutar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemAlbum = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(txtConsola);

        PanelEXP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelEXP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        PanelAST.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel2.setText("IMAGEN EXPRESION");

        jLabel3.setText("IMAGEN AST");

        jMenu1.setText("Archivo");

        itemNuevo.setText("Nuevo");
        itemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(itemNuevo);

        itemAbrir.setText("Abrir");
        itemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(itemAbrir);

        itemGuardar.setText("Guardar");
        itemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(itemGuardar);

        itemCerrar.setText("Cerrar");
        itemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarActionPerformed(evt);
            }
        });
        jMenu1.add(itemCerrar);

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(itemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Herramientas");

        itemEjecutar.setText("Ejecutar");
        itemEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEjecutarActionPerformed(evt);
            }
        });
        jMenu2.add(itemEjecutar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");

        itemAlbum.setText("Errores");
        itemAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlbumActionPerformed(evt);
            }
        });
        jMenu3.add(itemAlbum);

        jMenuItem2.setText("Abrir album");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Pestanas, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PanelEXP, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PanelAST, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(332, 332, 332))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelEXP, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addComponent(PanelAST, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pestanas, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para cerrar la aplicacion en su totalidad
     * @param evt 
     */
    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    /**
     * Metodo para abri una nueva pestana con editor de texto.
     * @param evt 
     */
    private void itemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevoActionPerformed
        // TODO add your handling code here:
        PestanaInterna pestana=new PestanaInterna();
        contadorPestanas++;
        Pestanas.addTab("Nuevo "+ contadorPestanas, pestana);
        
        //JOptionPane.showMessageDialog(null, Pestanas.getSelectedIndex());
        
    }//GEN-LAST:event_itemNuevoActionPerformed

    /**
     * Metodo para abrir documentos desde cualquier parte de la computador
     * Se utilizo un JFileChooser global llamado "seleccion".
     * Se crea un nuevo objeto de tipo PestanaInterna y se agrega en al Tab 
     * llamado "Pestanas"
     * @param evt 
     */
    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        // TODO add your handling code here:
        if(seleccion.showDialog(null, "ABRIR ARCHIVO") == JFileChooser.APPROVE_OPTION)
            {
            archivo = seleccion.getSelectedFile();
                if(archivo.canRead())
                {
                    String contenido = gestion.AbrirATexto(archivo);
                    PestanaInterna pestana=new PestanaInterna();
                    pestana.setTxtEntrada(contenido);
                    Pestanas.addTab(archivo.getName(), pestana);
                }
            }
        
    }//GEN-LAST:event_itemAbrirActionPerformed

    private void itemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarActionPerformed
        // TODO add your handling code here:
        if(Pestanas.getComponentCount()!=0)
        {
            if(seleccion.showDialog(null, "Guardar Clase")== JFileChooser.APPROVE_OPTION)
            {
                
                archivo=seleccion.getSelectedFile();
                PestanaInterna aux=(PestanaInterna)Pestanas.getSelectedComponent();
                int posicion=Pestanas.getSelectedIndex();
                String contenido=aux.getTxtEntrada();
                String respuesta =gestion.GuardarATexto(archivo, contenido);
                archivo = seleccion.getSelectedFile();

                if(respuesta!=null)
                {
                    JOptionPane.showMessageDialog(null, respuesta);
                    Pestanas.setTitleAt(posicion, seleccion.getName(archivo));
                  //  pestanas.setTitleAt(0, seleccion.getName(archivo));
                }else{
                    JOptionPane.showMessageDialog(null, "Error al guardar texto.");
                }

            }
        }else
        {
            JOptionPane.showMessageDialog(null, "No existe informacion por guardar");
        }
    }//GEN-LAST:event_itemGuardarActionPerformed

    /**
     * 
     * @param evt 
     */
    private void itemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarActionPerformed
        // TODO add your handling code here:
        PestanaInterna aux=(PestanaInterna)Pestanas.getSelectedComponent();
        int posicion=Pestanas.getSelectedIndex();
        if(aux.getTxtEntrada().equals(" "))
        {
            Pestanas.remove(posicion);
        }else
        {
            int respuesta= JOptionPane.showConfirmDialog(null, "Desea guardar los cambios?");
            switch (respuesta) {
                case 0:
                    itemGuardarActionPerformed(evt);
                    Pestanas.remove(posicion);
                    break;
                case 1:
                    Pestanas.remove(posicion);
                    break;
                case 2:
                    break;
                default:
                    break;
            }
            
        }
    }//GEN-LAST:event_itemCerrarActionPerformed

    Data data;
    private void itemEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEjecutarActionPerformed
        // TODO add your handling code here:
        PestanaInterna aux=(PestanaInterna)Pestanas.getSelectedComponent();
        
        if(aux.getTxtEntrada().length()!=0 || !aux.getTxtEntrada().equals(""))
        {
            Acciones.Compilador e = new Acciones.Compilador();
            data = new Data();
            e.analizar(aux.getTxtEntrada(), data);
            
            //txtConsola.setText(errores);
        }else
        {
            JOptionPane.showMessageDialog(null, "No existe texto por analizar");
        }
    }//GEN-LAST:event_itemEjecutarActionPerformed

    private void itemAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlbumActionPerformed
        // TODO add your handling code here:
        
        Varios var= new Varios();
        var.autoAbrir("/home/johnnybravo/SalidasDot_Pro2/Errores.html");
    }//GEN-LAST:event_itemAlbumActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Varios var= new Varios();
        var.autoAbrir("/home/johnnybravo/SalidasDot_Pro2");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * 
     * @param entrada Parametro de tipo String que contiene los errores de las listas
     * respectivas
     */
    public void mostrarErrores(ArrayList<ErrorT> lista)
    {
        //txtConsola.setText("\n"+entrada);
        if( !lista.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "HAY ERRORES");
        }else
        {
            JOptionPane.showMessageDialog(null, "NO HAY ERRORES");
        }
    }
    public void imprimirConsola(String entrada)
    {
        String aux=txtConsola.getText();
        this.txtConsola.setText(aux+"\n"+entrada);
    }
    
    /**
     * Metodo principal
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel PanelAST;
    public static javax.swing.JLabel PanelEXP;
    private javax.swing.JTabbedPane Pestanas;
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemAlbum;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JMenuItem itemEjecutar;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenuItem itemNuevo;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JEditorPane txtConsola;
    // End of variables declaration//GEN-END:variables
}
