
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jan 18 00:48:54 CST 2019
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int tokClla = 48;
  public static final int tokDiv = 35;
  public static final int tokDefinir = 3;
  public static final int tokFalso = 25;
  public static final int tokVerdadero = 24;
  public static final int tokString = 55;
  public static final int tokTexto = 6;
  public static final int tokDibujarAST = 21;
  public static final int tokApar = 45;
  public static final int tokCambiarA = 12;
  public static final int tokAlla = 47;
  public static final int tokImportar = 2;
  public static final int tokNumero = 54;
  public static final int tokMientrasQue = 17;
  public static final int tokMenosMenos = 33;
  public static final int tokDibujarExp = 22;
  public static final int tokDibujarTS = 23;
  public static final int tokMostrar = 20;
  public static final int tokComa = 51;
  public static final int tokDiferente = 40;
  public static final int tokEntero = 7;
  public static final int tokOr = 27;
  public static final int tokPotencia = 37;
  public static final int tokPrincipal = 26;
  public static final int EOF = 0;
  public static final int tokMenorIgual = 44;
  public static final int error = 1;
  public static final int tokIgual = 38;
  public static final int tokId = 56;
  public static final int tokContinuar = 19;
  public static final int tokMas = 30;
  public static final int tokBooleano = 5;
  public static final int tokDosp = 50;
  public static final int tokDecimal = 4;
  public static final int tokRetorno = 9;
  public static final int tokPara = 15;
  public static final int tokNoCumple = 13;
  public static final int tokMayorIgual = 43;
  public static final int tokEsFalso = 11;
  public static final int tokPor = 34;
  public static final int tokMenos = 32;
  public static final int tokMenor = 42;
  public static final int tokModulo = 36;
  public static final int tokPcoma = 49;
  public static final int tokMayor = 41;
  public static final int tokRomper = 18;
  public static final int tokAnd = 28;
  public static final int tokValor = 14;
  public static final int tokNot = 29;
  public static final int tokExtension = 53;
  public static final int tokEsVerdadero = 10;
  public static final int tokPunto = 52;
  public static final int tokVacio = 8;
  public static final int tokHastaQue = 16;
  public static final int tokCpar = 46;
  public static final int tokIgualIgual = 39;
  public static final int tokMasMas = 31;
}

