
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 12 02:21:11 CST 2019
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int tokClla = 49;
  public static final int tokDiv = 36;
  public static final int tokDefinir = 3;
  public static final int tokFalso = 26;
  public static final int tokVerdadero = 25;
  public static final int tokString = 56;
  public static final int tokCaracter = 8;
  public static final int tokTexto = 6;
  public static final int tokDibujarAST = 22;
  public static final int tokApar = 46;
  public static final int tokCambiarA = 13;
  public static final int tokAlla = 48;
  public static final int tokImportar = 2;
  public static final int tokNumero = 55;
  public static final int tokMientrasQue = 18;
  public static final int tokMenosMenos = 34;
  public static final int tokDibujarExp = 23;
  public static final int tokDibujarTS = 24;
  public static final int tokMostrar = 21;
  public static final int tokComa = 52;
  public static final int tokDiferente = 41;
  public static final int tokEntero = 7;
  public static final int tokOr = 28;
  public static final int tokPotencia = 38;
  public static final int tokPrincipal = 27;
  public static final int EOF = 0;
  public static final int tokMenorIgual = 45;
  public static final int error = 1;
  public static final int tokIgual = 39;
  public static final int tokId = 58;
  public static final int tokContinuar = 20;
  public static final int tokMas = 31;
  public static final int tokBooleano = 5;
  public static final int tokDosp = 51;
  public static final int tokDecimal = 4;
  public static final int tokRetorno = 10;
  public static final int tokPara = 16;
  public static final int tokNoCumple = 14;
  public static final int tokMayorIgual = 44;
  public static final int tokPor = 35;
  public static final int tokEsFalso = 12;
  public static final int tokMenos = 33;
  public static final int tokMenor = 43;
  public static final int tokModulo = 37;
  public static final int tokPcoma = 50;
  public static final int tokMayor = 42;
  public static final int tokChar = 57;
  public static final int tokRomper = 19;
  public static final int tokAnd = 29;
  public static final int tokValor = 15;
  public static final int tokNot = 30;
  public static final int tokExtension = 54;
  public static final int tokEsVerdadero = 11;
  public static final int tokPunto = 53;
  public static final int tokVacio = 9;
  public static final int tokHastaQue = 17;
  public static final int tokCpar = 47;
  public static final int tokIgualIgual = 40;
  public static final int tokMasMas = 32;
}

